### PR TITLE
Specs draft

### PR DESCRIPTION
**Pull request by stas**
This is a more substantial draft on the ingestors specs. It is pretty high-level, but this should help answer the questions we had regarding the challenges we face.

Some doubts/concerns:
1. Snoop provides a digest of every file it processes. Overall I think this is a smart way to handle children-parent relationships. The concern I have is that the folders do not actually have checksums. To overcome this I think we could generate an UUID as the main relationship identifier and provide the checksum only for files where available.
2. I explored the walker approach, and I think it needs to be part of the ingestor functionality (props @pudo). This way we can provide information on the execution time and have relevant status information. This is something related very much to the way Snoop operates. In order to provide a Snoop approach, I suggest providing an option to disable the walking part (i.e. walking is handled externally).
3. I dropeed the idea of having a strict format for resulted data. Please share any concerns here. I just couldn't see the benefit of introducing this component.
4. The _bundler_ concern which is present in the Aleph. I still need to review it closer, ideally by having some real fixtures.
5. The overall fixtures collection, Aleph has suggested this https://github.com/pudo/aleph/issues/129, if there are other fixtures I could review to include in the test suite, please send them over. :dove: 

@pudo @mgax I need your :eyes: for a final overview. I promise I'll be less needy once this is passed.

Thanks in advance!

### CODE REVIEW

**Comment by mgax** [comment]
I'm still concerned about the calling flow and separation of concerns: your proposal covers both analysis of files and the job control of spawning ingestors and saving the results. If we're to reuse the code for hoover, we'd like to keep our own job control, and use the ingestors as a library that analyzes files. If an ingestor says "look, there's subitems in this folder/email", it would be up to the caller to ask for them, if/when it needs them.

**Comment by mgax** [comment]
> I dropeed the idea of having a strict format for resulted data. Please share any concerns here. I just couldn't see the benefit of introducing this component.

I think it's useful to have some common fields - filename, mime type, checksum. Specific file types would have extra fields, e.g. emails have sender, subject, recipients. What would the result look like? A couple of examples would be great.

**Comment by stas** [comment]
> If we're to reuse the code for hoover, we'd like to keep our own job control, and use the ingestors as a library that analyses files.

Makes sense, disabling the job control will be an option.

In regards to the results, the generic attributes provided in the example could work for email too.
* document title, to become the subject
* document authors, to become the sender, receivers 
* text, to become the email body

If this is not ideal, extending an ingestor could introduce some extra attributes.

See:
https://github.com/alephdata/ingestors/pull/1/files#diff-0dc9a6461d00e2d7cc0517b0a48560e1R87

**Comment by pudo** [comment]
@mgax I agree with the spawning aspect: we want each file to be able to be processed on a different node (aleph prod at @occrp has seven workers currently), independently of it's parent, which will *not* know when the children have finished processing.

I agree that metadata needs to be split out as well, we cannot really do extraction without having a place to put and validate/parse it. Here's the current metadata schema for Aleph: 

https://github.com/pudo/aleph/blob/master/aleph/metadata/__init__.py#L41

This is more static that I'd like it to be, it'd be cool to sometimes be able to include extra info, like a Case Number for court cases etc.

**Pull request merged**
